popup-window
asadmisrani/portfoliofinishmobileversion.github.io pull request #14
Opened 2023-04-12 21:33 UTC by asadmisrani

Scripts.js file and README.md file were modified

Use basic JavaScript syntax.
Use JavaScript to manipulate DOM elements.
Use JavaScript events.
Understand how to parse a Figma design to create a UI.
Use objects to store and access data.

2023-04-12 21:41 UTC, Zuhaib042 reviewed
Hi @asadmisrani  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a commit from your partner. if he doesn't want to work with you then you can contact student success team by clicking on the support button on the dashboard.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-12 23:28 UTC, nedjwab requested changes
# Changes Required ♻️
### Hi @asadmisrani 

Nice job, you are almost there.

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## (Highlights) Good Points: :
- Good implementation of some of the project requirements  ✔
- GitHub flow was correctly used ✔.

## (Changes Required) Aspects to improve: ♻️
You did great implementing some of the project requirements, but you still have some issues: 
[ ] kindly fix the image in your pop up window , it's not showing up :

 Your design 👇 : 
![his](https://user-images.githubusercontent.com/62156607/231607561-a0d6110e-8ff7-41e9-af5c-2faf23dea4ab.PNG)


` note:check the URL in the javascript array`

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-04-12 23:52 UTC, asadmisrani commented
The image in the pop-up window was fixed, Now it's showing up.

On Thu, Apr 13, 2023 at 4:28 AM Nedjwa Bouraiou ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> Changes Required ♻️ Hi @asadmisrani <https://github.com/asadmisrani>
>
> Nice job, you are almost there.
>
>
> <https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966>
> (Highlights) Good Points: :
>
>    - Good implementation of some of the project requirements ✔
>    - GitHub flow was correctly used ✔.
>
> (Changes Required) Aspects to improve: ♻️
>
> You did great implementing some of the project requirements, but you still
> have some issues:
> [ ] kindly fix the image in your pop up window , it's not showing up :
>
> Your design 👇 :
> [image: his]
> <https://user-images.githubusercontent.com/62156607/231607561-a0d6110e-8ff7-41e9-af5c-2faf23dea4ab.PNG>
>
> note:check the URL in the javascript array
> [Optional] suggestions:
>
>    - Nothing to mention.
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> *Cheers and Happy coding!👏👏👏*
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear, and please remember to tag me in your question so I can
> receive the notification**
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have
> a limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/asadmisrani/portfoliofinishmobileversion.github.io/pull/14#pullrequestreview-1382265376>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYQGAKEM4UHGCR4PSJF5UNDXA43CVANCNFSM6AAAAAAW4HKBVE>
> .
> You are receiving this because you were mentioned.Message ID:
> <asadmisrani/portfoliofinishmobileversion.github.
> ***@***.***>
>

2023-04-13 01:12 UTC, Shedrack-Sunday requested changes
Hi @asadmisrani     👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well implementing the requirements,  However, there are a few you need to work on, to move to the next project. 💯

 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights
- Proper use CSS ✔️ 
- Nice README structure 👍 
- Moderate design 💯 
  
# Required Changes ♻️

- There's a bit content structure that defers i reference to the figma design given which the previous reviewer pointed 

_check the comment section for a detailed review_ 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-04-13 01:12 UTC, Shedrack-Sunday commented on script.js
>    {
- [ ] I can see you did make changes asked by the previous reviewer, however, the pictures on the pop-up after the first card are not still displaying. Please check the file paths

## View:
![image](https://user-images.githubusercontent.com/50990925/231619620-d0735ff6-5038-49a3-a070-53457a0fc3b7.png)

2023-04-13 02:26 UTC, asadmisrani commented
Are you not seeing this picture that is working fine and perfectly[image:
Screenshot_1.png]
?

On Thu, Apr 13, 2023 at 6:13 AM Shedrack Sunday ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @asadmisrani <https://github.com/asadmisrani> 👋
> CHANGES REQUIRED ♻️
>
> Great work on the project 👏
> You've done well implementing the requirements, However, there are a few
> you need to work on, to move to the next project. 💯
>
>
> <https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif>
> Highlights
>
>    - Proper use CSS ✔️
>    - Nice README structure 👍
>    - Moderate design 💯
>
> Required Changes ♻️
>
>    - There's a bit content structure that defers i reference to the figma
>    design given which the previous reviewer pointed
>
> *check the comment section for a detailed review*
> Optional suggestions
>
> Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.
>
> As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have
> a limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.
> ------------------------------
>
> In script.js
> <https://github.com/asadmisrani/portfoliofinishmobileversion.github.io/pull/14#discussion_r1164825550>
> :
>
> >  const popObjects = [
> -
> +  {
> +    title: 'Awesome books',
> +    subtitle: 'Microverse',
> +    experience: ['Front End Dev', '2023'],
> +    image: './images/screenshots/MainPage.png',
> +    image1: './images/screenshots/BooksList.png',
> +    description1: 'An application that allows users to add or remove books from a list, not subscription is needed nor online conection.',
> +    description: 'Awesome Books is a website that allows users to add/remove books from a list. It was achieved by using JavaScript objects and arrays. Dynamically modify the DOM and added basic events, using ES6 sintax, using modules into javascript code, and use of arrow functions.',
> +    tech: ['html', 'css', 'javaScript', 'Bootstrap', 'ES6 syntax'],
> +    seeLive: 'https://asadmisrani.github.io/AwesomeBooks/',
> +    seeSource: 'https://github.com/asadmisrani/AwesomeBooks-ES6',
> +    class: 'popCard1',
> +  },
>    {
>
>
>    - I can see you did make changes asked by the previous reviewer,
>    however, the pictures on the pop-up after the first card are not still
>    displaying. Please check the file paths
>
> View:
>
> [image: image]
> <https://user-images.githubusercontent.com/50990925/231619620-d0735ff6-5038-49a3-a070-53457a0fc3b7.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/asadmisrani/portfoliofinishmobileversion.github.io/pull/14#pullrequestreview-1382388076>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYQGAKAPTHHOUDE4BADCEGLXA5HKHANCNFSM6AAAAAAW4HKBVE>
> .
> You are receiving this because you were mentioned.Message ID:
> <asadmisrani/portfoliofinishmobileversion.github.
> ***@***.***>
>

2023-04-13 04:29 UTC, Nemwel-Boniface reviewed
## Hello @asadmisrani   👋,

I am Nemwel your reviewer.


## _This is an additional review as a result of the second opinion request._

I have received your second opinion request and inspected your project based on the complaint of the [last reviewer's](https://github.com/asadmisrani/portfoliofinishmobileversion.github.io/pull/14#discussion_r1164825550) (@Shedrack-Sunday ) request. 

**From my findings,** the changes requested by him are actually valid and indeed the images do not show on the popup. Below I have attached a screencast for you.

[Screencast from 13-04-2023 07:18:01 ASUBUHI.webm](https://user-images.githubusercontent.com/86318284/231652543-3066cd8b-24a9-4df1-b8fd-59be04689023.webm)

**Therefore** as the changes requested are actually valid, kindly ensure that you fix the images not displaying on all the cards by adding the ```image1``` field on all the objects.

Kindly make the required changes and when you are ready, please request another review in your dashboard.

In case anything is not 100% clear tag me @Nemwel-Boniface so that I get the notification.

Keep rocking 🚀!

2023-04-13 04:29 UTC, Nemwel-Boniface commented on script.js
>    {
- [ ] I went further to investigate and realized in your object for the first card has the field for ```image1``` which is not present in all other objects. When I duplicated the ```image1``` in the second and third objects, the popup displayed the images as it is supposed to. 

[Screencast from 13-04-2023 07:25:08 ASUBUHI.webm](https://user-images.githubusercontent.com/86318284/231652893-0c997b1b-d817-4ac6-b4a9-ea67a869c3ac.webm)

2023-04-13 08:40 UTC, asadmisrani commented
Done.
I have duplicated the first card has a field for Image1 which is now
present in all other objects. Now the popup displayed the images as it is
supposed to.

On Thu, Apr 13, 2023 at 9:29 AM Nemwel Boniface ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> Hello @asadmisrani <https://github.com/asadmisrani> 👋,
>
> I am Nemwel your reviewer.
> *This is an additional review as a result of the second opinion request.*
>
> I have received your second opinion request and inspected your project
> based on the complaint of the last reviewer's
> <https://github.com/asadmisrani/portfoliofinishmobileversion.github.io/pull/14#discussion_r1164825550>
> ***@***.*** <https://github.com/Shedrack-Sunday> ) request.
>
> *From my findings,* the changes requested by him are actually valid and
> indeed the images do not show on the popup. Below I have attached a
> screencast for you.
>
> Screencast from 13-04-2023 07:18:01 ASUBUHI.webm
> <https://user-images.githubusercontent.com/86318284/231652543-3066cd8b-24a9-4df1-b8fd-59be04689023.webm>
>
> *Therefore* as the changes requested are actually valid, kindly ensure
> that you fix the images not displaying on all the cards by adding the
> image1 field on all the objects.
>
> Kindly make the required changes and when you are ready, please request
> another review in your dashboard.
>
> In case anything is not 100% clear tag me @Nemwel-Boniface
> <https://github.com/Nemwel-Boniface> so that I get the notification.
>
> Keep rocking 🚀!
> ------------------------------
>
> In script.js
> <https://github.com/asadmisrani/portfoliofinishmobileversion.github.io/pull/14#discussion_r1164982323>
> :
>
> > +  {
> +    title: 'Awesome books',
> +    subtitle: 'Microverse',
> +    experience: ['Front End Dev', '2023'],
> +    image: './images/screenshots/MainPage.png',
> +    image1: './images/screenshots/BooksList.png',
> +    description1: 'An application that allows users to add or remove books from a list, not subscription is needed nor online conection.',
> +    description: 'Awesome Books is a website that allows users to add/remove books from a list. It was achieved by using JavaScript objects and arrays. Dynamically modify the DOM and added basic events, using ES6 sintax, using modules into javascript code, and use of arrow functions.',
> +    tech: ['html', 'css', 'javaScript', 'Bootstrap', 'ES6 syntax'],
> +    seeLive: 'https://asadmisrani.github.io/AwesomeBooks/',
> +    seeSource: 'https://github.com/asadmisrani/AwesomeBooks-ES6',
> +    class: 'popCard1',
> +  },
>    {
>
>
>    - I went further to investigate and realized in your object for the
>    first card has the field for image1 which is not present in all other
>    objects. When I duplicated the image1 in the second and third objects,
>    the popup displayed the images as it is supposed to.
>
> Screencast from 13-04-2023 07:25:08 ASUBUHI.webm
> <https://user-images.githubusercontent.com/86318284/231652893-0c997b1b-d817-4ac6-b4a9-ea67a869c3ac.webm>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/asadmisrani/portfoliofinishmobileversion.github.io/pull/14#pullrequestreview-1382601277>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYQGAKHHVNITQRGVTUYI36TXA56KNANCNFSM6AAAAAAW4HKBVE>
> .
> You are receiving this because you were mentioned.Message ID:
> <asadmisrani/portfoliofinishmobileversion.github.
> ***@***.***>
>

2023-04-13 09:06 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @asadmisrani , |
|Great work on making the changes requested by a previous reviewer 👏, You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. |
| <img src="https://media4.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif"/> |

## Highlights

- [ ].. ✅ Good design
- [ ].. ✅ Green linters
- [ ].. ✅ Good commit messges

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-13 09:06 UTC, joskalenda commented on script.js
> +    subtitle: 'Microverse',
- [ ] @asadmisrani, I think the same issue is still persisting, you should see how to fix it on the go, see the record below and make the necessary changes to it

![6](https://user-images.githubusercontent.com/77843050/231710408-5b2f4838-d72a-494c-a049-46143f2f224d.gif)
- Seeing this record, the image only displays on the 1st card, the rest does not show up.

2023-04-13 09:13 UTC, asadmisrani commented
All images are working fine I have checked.
what are you checking? what happened? to you I lost my 3 reviews and I
don't want to use extra reviews.
This is my live link check this everything is working fine:
https://asadmisrani.github.io/portfoliofinishmobileversion.github.io/
I don't know why are you doing this I am stuck with you.

On Thu, Apr 13, 2023 at 2:07 PM Jos Kalenda ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> STATUS: REQUIRED CHANGES ♻️
> Hi @asadmisrani <https://github.com/asadmisrani> ,
> Great work on making the changes requested by a previous reviewer 👏,
> You've done well implementing some of the requested changes, but there are
> still some which aren't been addressed yet.
>
> <https://camo.githubusercontent.com/2dccba3d35b40a2bc42531c9e057191a2c01cdc0fac348609e46b16cd1a6edf1/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f52657944344f64526948654c4443526145502f67697068792e676966>
> Highlights
>
>    - [ ].. ✅ Good design
>    - [ ].. ✅ Green linters
>    - [ ].. ✅ Good commit messges
>
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you take them into
> account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
> ------------------------------
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag ***@***.*** <https://github.com/joskalenda>)
> in your question so I can receive the notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
>
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In script.js
> <https://github.com/asadmisrani/portfoliofinishmobileversion.github.io/pull/14#discussion_r1165232096>
> :
>
> > +  {
> +    title: 'Awesome books',
> +    subtitle: 'Microverse',
>
>
>    - @asadmisrani <https://github.com/asadmisrani>, I think the same
>    issue is still persisting, you should see how to fix it on the go, see the
>    record below and make the necessary changes to it
>
> [image: 6]
> <https://user-images.githubusercontent.com/77843050/231710408-5b2f4838-d72a-494c-a049-46143f2f224d.gif>
>
>    - Seeing this record, the image only displays on the 1st card, the
>    rest does not show up.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/asadmisrani/portfoliofinishmobileversion.github.io/pull/14#pullrequestreview-1382981391>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYQGAKFKX22G2XSF75M2WIDXA663VANCNFSM6AAAAAAW4HKBVE>
> .
> You are receiving this because you were mentioned.Message ID:
> <asadmisrani/portfoliofinishmobileversion.github.
> ***@***.***>
>

2023-04-13 11:02 UTC, merged

2023-04-13 12:10 UTC, Nemwel-Boniface reviewed
## Hello @asadmisrani   👋,

I am Nemwel your reviewer.


## _This is an additional review as a result of the second opinion request._

**Note:** When you request for a second opinion request, you are required to be patient and not close/ merge a PR or request for another review in your dashboard, or make any new commits until the second opinion request has been resolved unless it will alter the outcome of the second opinion request.

I have received your second opinion request and inspected it and from my end the popup does show the images as it is supposed to. For some reason the issue might be arising from the code reviewer's end.

**Note** However, I believe that there is room for improvement and you could consider giving the popup a height of 100vh so that is fits on the whole page without you having to scroll all the way up to view the popup. Video shown below:

[Screencast from 13-04-2023 03:08:37 ALASIRI.webm](https://user-images.githubusercontent.com/86318284/231753852-7a65016f-4b93-4837-abac-92901f9cee26.webm)


As this was the only reason that your project was not approved it will be approved as soon as possible.
Please note that since we will approve it manually so this could take a few hours!

In case anything is not 100% clear tag me @Nemwel-Boniface so that I get the notification.

Keep rocking 🚀!

2023-04-13 15:05 UTC, franclobo commented
Hi @asadmisrani, 

# STATUS: APPROVED 😃 

![git-merge](https://user-images.githubusercontent.com/58642949/231802574-0fdedef2-a347-4f76-8941-37fa17eba816.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Correct Github flow ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._